repos:
  # ---------------------------
  # General purpose pre-commit hooks
  # ---------------------------
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-yaml
      - id: check-json
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files

  # ---------------------------
  # Golang checks
  # ---------------------------
  - repo: https://github.com/golangci/golangci-lint
    rev: v2.6.2
    hooks:
      - id: golangci-lint-full
      - id: golangci-lint-fmt

  # ---------------------------
  # Security checks
  # ---------------------------
  - repo: https://github.com/gitleaks/gitleaks
    rev: v8.29.0
    hooks:
      - id: gitleaks
